import React from 'react'
import {Card,Table} from 'antd'
export default class BasicTable extends React.Component{
    state={}
    componentDidMount(){
        const dataSource = [
            {
                id:'0',
                userName:'Yiqing',
                sex:'1',
                state:'1',
                interest:'1',
                birthday:'2000-01-01',
                address:'你心里',
                time:'09:00'
            },
            {
                id:'1',
                userName:'Lingjun',
                sex:'1',
                state:'1',
                interest:'1',
                birthday:'2000-01-01',
                address:'你心里',
                time:'09:00'
            },
            {
                id:'3',
                userName:'Miao',
                sex:'1',
                state:'1',
                interest:'1',
                birthday:'2000-01-01',
                address:'你心里',
                time:'09:00'
            }
        ]
        this.setState({
            dataSource
        })
    }
    render(){
        const columns = [
            {
                title:'id',
                dataIndex:'id'
            },
            {
                title:'用户名',
                dataIndex:'userName'
            },
            {
                title:'性别',
                dataIndex:'sex'
            },
            {
                title:'状态',
                dataIndex:'state'
            },
            {
                title:'生日',
                dataIndex:'birthday'
            },
            {
                title:'地址',
                dataIndex:'address'
            },
            {
                title:'早起时间',
                dataIndex:'time'
            }
        ]
        return(
            <div>
                <Card title="基础表格">
                    <Table
                        columns={columns} 
                        dataSource={this.state.dataSource}   
                        pagination={false}
                    />
                </Card>
            </div>
        )
    }
}